//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleDnsCrypt.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleDnsCrypt.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die License ähnelt.
        /// </summary>
        internal static string about_license {
            get {
                return ResourceManager.GetString("about_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Special Thanks to ähnelt.
        /// </summary>
        internal static string about_special_thanks {
            get {
                return ResourceManager.GetString("about_special_thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - for funding this project! ähnelt.
        /// </summary>
        internal static string about_thanks_bytejail_text {
            get {
                return ResourceManager.GetString("about_thanks_bytejail_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The EAM GmbH and bytejail - https://bytejail.com ähnelt.
        /// </summary>
        internal static string about_thanks_bytejail_title {
            get {
                return ResourceManager.GetString("about_thanks_bytejail_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - for developing libsodium and DNSCrypt! ähnelt.
        /// </summary>
        internal static string about_thanks_frank_text {
            get {
                return ResourceManager.GetString("about_thanks_frank_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frank Denis (@jedisct1) - https://dnscrypt.org ähnelt.
        /// </summary>
        internal static string about_thanks_frank_title {
            get {
                return ResourceManager.GetString("about_thanks_frank_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Used software ähnelt.
        /// </summary>
        internal static string about_used_software {
            get {
                return ResourceManager.GetString("about_used_software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Debug Mode ähnelt.
        /// </summary>
        internal static string advanced_settings_debug_title {
            get {
                return ResourceManager.GetString("advanced_settings_debug_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you want this computer to act as gateway device for others (eg: smartphones or other computers) ähnelt.
        /// </summary>
        internal static string advanced_settings_global_resolver_text {
            get {
                return ResourceManager.GetString("advanced_settings_global_resolver_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Global Resolver ähnelt.
        /// </summary>
        internal static string advanced_settings_global_resolver_title {
            get {
                return ResourceManager.GetString("advanced_settings_global_resolver_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open plugin manager ähnelt.
        /// </summary>
        internal static string advanced_settings_plugins_button {
            get {
                return ResourceManager.GetString("advanced_settings_plugins_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable or disable extra settings with plugins ähnelt.
        /// </summary>
        internal static string advanced_settings_plugins_text {
            get {
                return ResourceManager.GetString("advanced_settings_plugins_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugins ähnelt.
        /// </summary>
        internal static string advanced_settings_plugins_title {
            get {
                return ResourceManager.GetString("advanced_settings_plugins_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download List ähnelt.
        /// </summary>
        internal static string advanced_settings_refresh_resolver_button {
            get {
                return ResourceManager.GetString("advanced_settings_refresh_resolver_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh the list of public resolvers (all downloads are validated with a minisgn signature) ähnelt.
        /// </summary>
        internal static string advanced_settings_refresh_resolver_text {
            get {
                return ResourceManager.GetString("advanced_settings_refresh_resolver_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh public resolver list ähnelt.
        /// </summary>
        internal static string advanced_settings_refresh_resolver_title {
            get {
                return ResourceManager.GetString("advanced_settings_refresh_resolver_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use TCP port 443 instead of UDP port 443 (TCP is slower than UDP) ähnelt.
        /// </summary>
        internal static string advanced_settings_transport_tcp_text {
            get {
                return ResourceManager.GetString("advanced_settings_transport_tcp_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transport Settings ähnelt.
        /// </summary>
        internal static string advanced_settings_transport_tcp_title {
            get {
                return ResourceManager.GetString("advanced_settings_transport_tcp_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uninstall all services ähnelt.
        /// </summary>
        internal static string advanced_settings_uninstall_button {
            get {
                return ResourceManager.GetString("advanced_settings_uninstall_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove all installed windows services ähnelt.
        /// </summary>
        internal static string advanced_settings_uninstall_text {
            get {
                return ResourceManager.GetString("advanced_settings_uninstall_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uninstall Services ähnelt.
        /// </summary>
        internal static string advanced_settings_uninstall_title {
            get {
                return ResourceManager.GetString("advanced_settings_uninstall_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DNSSEC ähnelt.
        /// </summary>
        internal static string default_settings_dnssec {
            get {
                return ResourceManager.GetString("default_settings_dnssec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name (FQDN) ähnelt.
        /// </summary>
        internal static string default_settings_name {
            get {
                return ResourceManager.GetString("default_settings_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Network Cards ähnelt.
        /// </summary>
        internal static string default_settings_network_cards {
            get {
                return ResourceManager.GetString("default_settings_network_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Logs ähnelt.
        /// </summary>
        internal static string default_settings_no_logs {
            get {
                return ResourceManager.GetString("default_settings_no_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Primary Resolver ähnelt.
        /// </summary>
        internal static string default_settings_primary_header {
            get {
                return ResourceManager.GetString("default_settings_primary_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Primary DNSCrypt Service ähnelt.
        /// </summary>
        internal static string default_settings_primary_service {
            get {
                return ResourceManager.GetString("default_settings_primary_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The first resolver ähnelt.
        /// </summary>
        internal static string default_settings_primary_text {
            get {
                return ResourceManager.GetString("default_settings_primary_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Public Key ähnelt.
        /// </summary>
        internal static string default_settings_public_key {
            get {
                return ResourceManager.GetString("default_settings_public_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resolver ähnelt.
        /// </summary>
        internal static string default_settings_resolver {
            get {
                return ResourceManager.GetString("default_settings_resolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Secondary Resolver ähnelt.
        /// </summary>
        internal static string default_settings_secondary_header {
            get {
                return ResourceManager.GetString("default_settings_secondary_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Secondary DNSCrypt Service ähnelt.
        /// </summary>
        internal static string default_settings_secondary_service {
            get {
                return ResourceManager.GetString("default_settings_secondary_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The second resolver (optional) ähnelt.
        /// </summary>
        internal static string default_settings_secondary_text {
            get {
                return ResourceManager.GetString("default_settings_secondary_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server Address ähnelt.
        /// </summary>
        internal static string default_settings_server_address {
            get {
                return ResourceManager.GetString("default_settings_server_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Services ähnelt.
        /// </summary>
        internal static string default_settings_services {
            get {
                return ResourceManager.GetString("default_settings_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show hidden cards ähnelt.
        /// </summary>
        internal static string default_settings_show_hidden_cards {
            get {
                return ResourceManager.GetString("default_settings_show_hidden_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string dialog_error_title {
            get {
                return ResourceManager.GetString("dialog_error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You must run this application as administrator. ähnelt.
        /// </summary>
        internal static string dialog_message_bad_privileges {
            get {
                return ResourceManager.GetString("dialog_message_bad_privileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can`t load: {0} or {1}. ähnelt.
        /// </summary>
        internal static string dialog_message_missing_file {
            get {
                return ResourceManager.GetString("dialog_message_missing_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There were not found all the necessary files in dnscrypt proxy folder, reinstalling the application is recommended. ähnelt.
        /// </summary>
        internal static string dialog_message_missing_proxy_files {
            get {
                return ResourceManager.GetString("dialog_message_missing_proxy_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to refresh the resolver list. ähnelt.
        /// </summary>
        internal static string dialog_message_refresh_failed {
            get {
                return ResourceManager.GetString("dialog_message_refresh_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to remove all installed windows services? ähnelt.
        /// </summary>
        internal static string dialog_message_uninstall {
            get {
                return ResourceManager.GetString("dialog_message_uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string dialog_plugins_save_button_tooltip {
            get {
                return ResourceManager.GetString("dialog_plugins_save_button_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successful ähnelt.
        /// </summary>
        internal static string dialog_success_title {
            get {
                return ResourceManager.GetString("dialog_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uninstall Services ähnelt.
        /// </summary>
        internal static string dialog_uninstall_title {
            get {
                return ResourceManager.GetString("dialog_uninstall_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        internal static string dialog_warning_title {
            get {
                return ResourceManager.GetString("dialog_warning_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IPv6 disabled ähnelt.
        /// </summary>
        internal static string global_ipv6_disabled {
            get {
                return ResourceManager.GetString("global_ipv6_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If IPv6 connectivity is not available on your network, this plugin avoids waiting for responses about IPv6 addresses from upstream resolvers. This can improve your web browsing experience. ähnelt.
        /// </summary>
        internal static string ipv6_speed_plugin_text {
            get {
                return ResourceManager.GetString("ipv6_speed_plugin_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speed up on missing IPv6 ähnelt.
        /// </summary>
        internal static string ipv6_speed_plugin_title {
            get {
                return ResourceManager.GetString("ipv6_speed_plugin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a log folder ähnelt.
        /// </summary>
        internal static string log_plugin_select_folder {
            get {
                return ResourceManager.GetString("log_plugin_select_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This plugin logs the DNS queries received by the proxy.
        ///The logs are stored in a local file. ähnelt.
        /// </summary>
        internal static string log_plugin_text {
            get {
                return ResourceManager.GetString("log_plugin_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logging ähnelt.
        /// </summary>
        internal static string log_plugin_title {
            get {
                return ResourceManager.GetString("log_plugin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        internal static string tab_about {
            get {
                return ResourceManager.GetString("tab_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advanced Settings ähnelt.
        /// </summary>
        internal static string tab_advanced_settings {
            get {
                return ResourceManager.GetString("tab_advanced_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standard Settings ähnelt.
        /// </summary>
        internal static string tab_standard_settings {
            get {
                return ResourceManager.GetString("tab_standard_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available extensions ähnelt.
        /// </summary>
        internal static string window_plugin_title {
            get {
                return ResourceManager.GetString("window_plugin_title", resourceCulture);
            }
        }
    }
}
