//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleDnsCrypt.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleDnsCrypt.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die License ähnelt.
        /// </summary>
        internal static string about_license {
            get {
                return ResourceManager.GetString("about_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Special Thanks to ähnelt.
        /// </summary>
        internal static string about_special_thanks {
            get {
                return ResourceManager.GetString("about_special_thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - for funding this project! ähnelt.
        /// </summary>
        internal static string about_thanks_bytejail_text {
            get {
                return ResourceManager.GetString("about_thanks_bytejail_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The EAM GmbH and bytejail - https://bytejail.com ähnelt.
        /// </summary>
        internal static string about_thanks_bytejail_title {
            get {
                return ResourceManager.GetString("about_thanks_bytejail_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - for developing libsodium and DNSCrypt! ähnelt.
        /// </summary>
        internal static string about_thanks_frank_text {
            get {
                return ResourceManager.GetString("about_thanks_frank_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frank Denis (@jedisct1) - https://dnscrypt.org ähnelt.
        /// </summary>
        internal static string about_thanks_frank_title {
            get {
                return ResourceManager.GetString("about_thanks_frank_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Used software ähnelt.
        /// </summary>
        internal static string about_used_software {
            get {
                return ResourceManager.GetString("about_used_software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Debug Mode ähnelt.
        /// </summary>
        internal static string advanced_settings_debug_title {
            get {
                return ResourceManager.GetString("advanced_settings_debug_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you want this computer to act as gateway device for others (eg: smartphones or other computers) ähnelt.
        /// </summary>
        internal static string advanced_settings_global_resolver_text {
            get {
                return ResourceManager.GetString("advanced_settings_global_resolver_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Global Resolver ähnelt.
        /// </summary>
        internal static string advanced_settings_global_resolver_title {
            get {
                return ResourceManager.GetString("advanced_settings_global_resolver_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open plugin manager ähnelt.
        /// </summary>
        internal static string advanced_settings_plugins_button {
            get {
                return ResourceManager.GetString("advanced_settings_plugins_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable or disable extra settings with plugins ähnelt.
        /// </summary>
        internal static string advanced_settings_plugins_text {
            get {
                return ResourceManager.GetString("advanced_settings_plugins_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugins ähnelt.
        /// </summary>
        internal static string advanced_settings_plugins_title {
            get {
                return ResourceManager.GetString("advanced_settings_plugins_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download List ähnelt.
        /// </summary>
        internal static string advanced_settings_refresh_resolver_button {
            get {
                return ResourceManager.GetString("advanced_settings_refresh_resolver_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh the list of public resolvers (all downloads are validated with a minisgn signature) ähnelt.
        /// </summary>
        internal static string advanced_settings_refresh_resolver_text {
            get {
                return ResourceManager.GetString("advanced_settings_refresh_resolver_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh public resolver list ähnelt.
        /// </summary>
        internal static string advanced_settings_refresh_resolver_title {
            get {
                return ResourceManager.GetString("advanced_settings_refresh_resolver_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use TCP port 443 instead of UDP port 443 (TCP is slower than UDP) ähnelt.
        /// </summary>
        internal static string advanced_settings_transport_tcp_text {
            get {
                return ResourceManager.GetString("advanced_settings_transport_tcp_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transport Settings ähnelt.
        /// </summary>
        internal static string advanced_settings_transport_tcp_title {
            get {
                return ResourceManager.GetString("advanced_settings_transport_tcp_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uninstall all services ähnelt.
        /// </summary>
        internal static string advanced_settings_uninstall_button {
            get {
                return ResourceManager.GetString("advanced_settings_uninstall_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove all installed windows services ähnelt.
        /// </summary>
        internal static string advanced_settings_uninstall_text {
            get {
                return ResourceManager.GetString("advanced_settings_uninstall_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uninstall Services ähnelt.
        /// </summary>
        internal static string advanced_settings_uninstall_title {
            get {
                return ResourceManager.GetString("advanced_settings_uninstall_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die building list . . . ähnelt.
        /// </summary>
        internal static string blacklist_building_list {
            get {
                return ResourceManager.GetString("blacklist_building_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new address rule ähnelt.
        /// </summary>
        internal static string blacklist_button_add_address {
            get {
                return ResourceManager.GetString("blacklist_button_add_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new local domain rule ähnelt.
        /// </summary>
        internal static string blacklist_button_add_local_domain {
            get {
                return ResourceManager.GetString("blacklist_button_add_local_domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new remote domain rule (URL) ähnelt.
        /// </summary>
        internal static string blacklist_button_add_remote_domain {
            get {
                return ResourceManager.GetString("blacklist_button_add_remote_domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build address blacklist ähnelt.
        /// </summary>
        internal static string blacklist_button_build_address {
            get {
                return ResourceManager.GetString("blacklist_button_build_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build domain blacklist ähnelt.
        /// </summary>
        internal static string blacklist_button_build_domain {
            get {
                return ResourceManager.GetString("blacklist_button_build_domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove address entry ähnelt.
        /// </summary>
        internal static string blacklist_button_remove_address {
            get {
                return ResourceManager.GetString("blacklist_button_remove_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove domain entry ähnelt.
        /// </summary>
        internal static string blacklist_button_remove_domain {
            get {
                return ResourceManager.GetString("blacklist_button_remove_domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select address blacklist file ähnelt.
        /// </summary>
        internal static string blacklist_button_select_address_blacklist {
            get {
                return ResourceManager.GetString("blacklist_button_select_address_blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select domain blacklist file ähnelt.
        /// </summary>
        internal static string blacklist_button_select_domain_blacklist {
            get {
                return ResourceManager.GetString("blacklist_button_select_domain_blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die entries ähnelt.
        /// </summary>
        internal static string blacklist_entries {
            get {
                return ResourceManager.GetString("blacklist_entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to set blacklist ähnelt.
        /// </summary>
        internal static string blacklist_modal_empty_list_header {
            get {
                return ResourceManager.GetString("blacklist_modal_empty_list_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A blacklist file can not be empty ähnelt.
        /// </summary>
        internal static string blacklist_modal_empty_list_text {
            get {
                return ResourceManager.GetString("blacklist_modal_empty_list_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New address rule ähnelt.
        /// </summary>
        internal static string blacklist_modal_new_address_rule_header {
            get {
                return ResourceManager.GetString("blacklist_modal_new_address_rule_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Example: 172.16.144.8, 172.16.*, [fdb2:cd9e:c9f8:861a:c1ab:94e3:ef95:1ec0] ähnelt.
        /// </summary>
        internal static string blacklist_modal_new_address_rule_text {
            get {
                return ResourceManager.GetString("blacklist_modal_new_address_rule_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New local domain rule ähnelt.
        /// </summary>
        internal static string blacklist_modal_new_local_domain_rule_header {
            get {
                return ResourceManager.GetString("blacklist_modal_new_local_domain_rule_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Example: *.example.com, ads.*, *sex* ähnelt.
        /// </summary>
        internal static string blacklist_modal_new_local_domain_rule_text {
            get {
                return ResourceManager.GetString("blacklist_modal_new_local_domain_rule_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New remote domain rule ähnelt.
        /// </summary>
        internal static string blacklist_modal_new_remote_domain_rule_header {
            get {
                return ResourceManager.GetString("blacklist_modal_new_remote_domain_rule_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Example: https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt ähnelt.
        /// </summary>
        internal static string blacklist_modal_new_remote_domain_rule_text {
            get {
                return ResourceManager.GetString("blacklist_modal_new_remote_domain_rule_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Block addresses ähnelt.
        /// </summary>
        internal static string block_plugin_sub_addresses_header {
            get {
                return ResourceManager.GetString("block_plugin_sub_addresses_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Block addresses with custom rules (eg: 10.1.4.99, 172.16.*) ähnelt.
        /// </summary>
        internal static string block_plugin_sub_addresses_text {
            get {
                return ResourceManager.GetString("block_plugin_sub_addresses_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Block domains ähnelt.
        /// </summary>
        internal static string block_plugin_sub_domains_header {
            get {
                return ResourceManager.GetString("block_plugin_sub_domains_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Block domains with local rules or remote files ähnelt.
        /// </summary>
        internal static string block_plugin_sub_domains_text {
            get {
                return ResourceManager.GetString("block_plugin_sub_domains_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This plugin returns a REFUSED response if the query name is in a list of blacklisted names, or if at least one of the returned IP addresses happens to be in a list of blacklisted IPs. ähnelt.
        /// </summary>
        internal static string block_plugin_text {
            get {
                return ResourceManager.GetString("block_plugin_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Block addresses and domains ähnelt.
        /// </summary>
        internal static string block_plugin_title {
            get {
                return ResourceManager.GetString("block_plugin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die seconds ähnelt.
        /// </summary>
        internal static string cache_plugin_seconds {
            get {
                return ResourceManager.GetString("cache_plugin_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A simple, zero-configuration DNS response cache. ähnelt.
        /// </summary>
        internal static string cache_plugin_text {
            get {
                return ResourceManager.GetString("cache_plugin_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DNS response cache ähnelt.
        /// </summary>
        internal static string cache_plugin_title {
            get {
                return ResourceManager.GetString("cache_plugin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TTL (cache time) ähnelt.
        /// </summary>
        internal static string cache_plugin_ttl {
            get {
                return ResourceManager.GetString("cache_plugin_ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die cancel ähnelt.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get some extra info about the resolvers (only IPv4) ähnelt.
        /// </summary>
        internal static string default_settings_analyse_button_tooltip {
            get {
                return ResourceManager.GetString("default_settings_analyse_button_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DNSSEC ähnelt.
        /// </summary>
        internal static string default_settings_dnssec {
            get {
                return ResourceManager.GetString("default_settings_dnssec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DNSCrypt will listen on this port (default: 53) ähnelt.
        /// </summary>
        internal static string default_settings_info_port {
            get {
                return ResourceManager.GetString("default_settings_info_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name (FQDN) ähnelt.
        /// </summary>
        internal static string default_settings_name {
            get {
                return ResourceManager.GetString("default_settings_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Network Cards ähnelt.
        /// </summary>
        internal static string default_settings_network_cards {
            get {
                return ResourceManager.GetString("default_settings_network_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Logs ähnelt.
        /// </summary>
        internal static string default_settings_no_logs {
            get {
                return ResourceManager.GetString("default_settings_no_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Primary Resolver ähnelt.
        /// </summary>
        internal static string default_settings_primary_header {
            get {
                return ResourceManager.GetString("default_settings_primary_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Primary DNSCrypt Service ähnelt.
        /// </summary>
        internal static string default_settings_primary_service {
            get {
                return ResourceManager.GetString("default_settings_primary_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The first resolver ähnelt.
        /// </summary>
        internal static string default_settings_primary_text {
            get {
                return ResourceManager.GetString("default_settings_primary_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Public Key ähnelt.
        /// </summary>
        internal static string default_settings_public_key {
            get {
                return ResourceManager.GetString("default_settings_public_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resolver ähnelt.
        /// </summary>
        internal static string default_settings_resolver {
            get {
                return ResourceManager.GetString("default_settings_resolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string default_settings_save_port {
            get {
                return ResourceManager.GetString("default_settings_save_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Secondary Resolver ähnelt.
        /// </summary>
        internal static string default_settings_secondary_header {
            get {
                return ResourceManager.GetString("default_settings_secondary_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Secondary DNSCrypt Service ähnelt.
        /// </summary>
        internal static string default_settings_secondary_service {
            get {
                return ResourceManager.GetString("default_settings_secondary_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The second resolver (optional) ähnelt.
        /// </summary>
        internal static string default_settings_secondary_text {
            get {
                return ResourceManager.GetString("default_settings_secondary_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server Address ähnelt.
        /// </summary>
        internal static string default_settings_server_address {
            get {
                return ResourceManager.GetString("default_settings_server_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Services ähnelt.
        /// </summary>
        internal static string default_settings_services {
            get {
                return ResourceManager.GetString("default_settings_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show hidden cards ähnelt.
        /// </summary>
        internal static string default_settings_show_hidden_cards {
            get {
                return ResourceManager.GetString("default_settings_show_hidden_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string dialog_error_title {
            get {
                return ResourceManager.GetString("dialog_error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You must run this application as administrator. ähnelt.
        /// </summary>
        internal static string dialog_message_bad_privileges {
            get {
                return ResourceManager.GetString("dialog_message_bad_privileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can`t load: {0} or {1}. ähnelt.
        /// </summary>
        internal static string dialog_message_missing_file {
            get {
                return ResourceManager.GetString("dialog_message_missing_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not all the necessary files in dnscrypt proxy folder are found, reinstalling the application is recommended. ähnelt.
        /// </summary>
        internal static string dialog_message_missing_proxy_files {
            get {
                return ResourceManager.GetString("dialog_message_missing_proxy_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to refresh the resolver list. ähnelt.
        /// </summary>
        internal static string dialog_message_refresh_failed {
            get {
                return ResourceManager.GetString("dialog_message_refresh_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to remove all installed windows services? ähnelt.
        /// </summary>
        internal static string dialog_message_uninstall {
            get {
                return ResourceManager.GetString("dialog_message_uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is a new Simple DNSCrypt version ({0}) available. The update is marked as critical, so you really should do the update now! Do you want to update now? ähnelt.
        /// </summary>
        internal static string dialog_message_update_critical_text {
            get {
                return ResourceManager.GetString("dialog_message_update_critical_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Critical Application Update ähnelt.
        /// </summary>
        internal static string dialog_message_update_critical_title {
            get {
                return ResourceManager.GetString("dialog_message_update_critical_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is a new Simple DNSCrypt version ({0}) available. Do you want to update now? ähnelt.
        /// </summary>
        internal static string dialog_message_update_standard_text {
            get {
                return ResourceManager.GetString("dialog_message_update_standard_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application Update ähnelt.
        /// </summary>
        internal static string dialog_message_update_standard_title {
            get {
                return ResourceManager.GetString("dialog_message_update_standard_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string dialog_plugins_save_button_tooltip {
            get {
                return ResourceManager.GetString("dialog_plugins_save_button_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successful ähnelt.
        /// </summary>
        internal static string dialog_success_title {
            get {
                return ResourceManager.GetString("dialog_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uninstall Services ähnelt.
        /// </summary>
        internal static string dialog_uninstall_title {
            get {
                return ResourceManager.GetString("dialog_uninstall_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installer ähnelt.
        /// </summary>
        internal static string dialog_update_installer {
            get {
                return ResourceManager.GetString("dialog_update_installer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signature ähnelt.
        /// </summary>
        internal static string dialog_update_signature {
            get {
                return ResourceManager.GetString("dialog_update_signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloads ähnelt.
        /// </summary>
        internal static string dialog_update_title {
            get {
                return ResourceManager.GetString("dialog_update_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        internal static string dialog_warning_title {
            get {
                return ResourceManager.GetString("dialog_warning_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domains.
        /// </summary>
        internal static string forwarding_plugin_domains {
            get {
                return ResourceManager.GetString("forwarding_plugin_domains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolvers.
        /// </summary>
        internal static string forwarding_plugin_resolvers {
            get {
                return ResourceManager.GetString("forwarding_plugin_resolvers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin forwards queries for a specific set of domain names to one or more non-DNSCrypt resolvers. This can be used to send queries for private domains to the router or to an internal DNS server..
        /// </summary>
        internal static string forwarding_plugin_text {
            get {
                return ResourceManager.GetString("forwarding_plugin_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarding.
        /// </summary>
        internal static string forwarding_plugin_title {
            get {
                return ResourceManager.GetString("forwarding_plugin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv6 disabled.
        /// </summary>
        internal static string global_ipv6_disabled {
            get {
                return ResourceManager.GetString("global_ipv6_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If IPv6 connectivity is not available on your network, this plugin avoids waiting for responses about IPv6 addresses from upstream resolvers. This can improve your web browsing experience. ähnelt.
        /// </summary>
        internal static string ipv6_speed_plugin_text {
            get {
                return ResourceManager.GetString("ipv6_speed_plugin_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speed up on missing IPv6 ähnelt.
        /// </summary>
        internal static string ipv6_speed_plugin_title {
            get {
                return ResourceManager.GetString("ipv6_speed_plugin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add selected to local domain blacklist ähnelt.
        /// </summary>
        internal static string log_button_add_to_blacklist {
            get {
                return ResourceManager.GetString("log_button_add_to_blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entries in LiveLog: ähnelt.
        /// </summary>
        internal static string log_entries {
            get {
                return ResourceManager.GetString("log_entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Blacklist Entry ähnelt.
        /// </summary>
        internal static string log_modal_add_rule_header {
            get {
                return ResourceManager.GetString("log_modal_add_rule_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can modify the entry before you add them to the blacklist:  ähnelt.
        /// </summary>
        internal static string log_modal_add_rule_text {
            get {
                return ResourceManager.GetString("log_modal_add_rule_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing Logfile ähnelt.
        /// </summary>
        internal static string log_modal_no_log_file_header {
            get {
                return ResourceManager.GetString("log_modal_no_log_file_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is no logfile to show. Please enable the logging plugin first. ähnelt.
        /// </summary>
        internal static string log_modal_no_log_file_text {
            get {
                return ResourceManager.GetString("log_modal_no_log_file_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a log folder ähnelt.
        /// </summary>
        internal static string log_plugin_select_folder {
            get {
                return ResourceManager.GetString("log_plugin_select_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This plugin logs the DNS queries received by the proxy.
        ///The logs are stored in a local file. ähnelt.
        /// </summary>
        internal static string log_plugin_text {
            get {
                return ResourceManager.GetString("log_plugin_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logging ähnelt.
        /// </summary>
        internal static string log_plugin_title {
            get {
                return ResourceManager.GetString("log_plugin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Source: ähnelt.
        /// </summary>
        internal static string log_source {
            get {
                return ResourceManager.GetString("log_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die no ähnelt.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        internal static string tab_about {
            get {
                return ResourceManager.GetString("tab_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advanced Settings ähnelt.
        /// </summary>
        internal static string tab_advanced_settings {
            get {
                return ResourceManager.GetString("tab_advanced_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Block and Blacklist ähnelt.
        /// </summary>
        internal static string tab_block {
            get {
                return ResourceManager.GetString("tab_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Live Log ähnelt.
        /// </summary>
        internal static string tab_log {
            get {
                return ResourceManager.GetString("tab_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standard Settings ähnelt.
        /// </summary>
        internal static string tab_standard_settings {
            get {
                return ResourceManager.GetString("tab_standard_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available extensions ähnelt.
        /// </summary>
        internal static string window_plugin_title {
            get {
                return ResourceManager.GetString("window_plugin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stay tuned ähnelt.
        /// </summary>
        internal static string window_update_title {
            get {
                return ResourceManager.GetString("window_update_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die yes ähnelt.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
