//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleDnsCrypt.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleDnsCrypt.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string about_license {
            get {
                return ResourceManager.GetString("about_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Thanks to.
        /// </summary>
        internal static string about_special_thanks {
            get {
                return ResourceManager.GetString("about_special_thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - for funding this project!.
        /// </summary>
        internal static string about_thanks_bytejail_text {
            get {
                return ResourceManager.GetString("about_thanks_bytejail_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EAM GmbH and bytejail - https://bytejail.com.
        /// </summary>
        internal static string about_thanks_bytejail_title {
            get {
                return ResourceManager.GetString("about_thanks_bytejail_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - for developing libsodium and DNSCrypt!.
        /// </summary>
        internal static string about_thanks_frank_text {
            get {
                return ResourceManager.GetString("about_thanks_frank_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frank Denis (@jedisct1) - https://dnscrypt.org.
        /// </summary>
        internal static string about_thanks_frank_title {
            get {
                return ResourceManager.GetString("about_thanks_frank_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used software.
        /// </summary>
        internal static string about_used_software {
            get {
                return ResourceManager.GetString("about_used_software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Mode.
        /// </summary>
        internal static string advanced_settings_debug_title {
            get {
                return ResourceManager.GetString("advanced_settings_debug_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want this computer to act as gateway device for others (eg: smartphones or other computers).
        /// </summary>
        internal static string advanced_settings_global_resolver_text {
            get {
                return ResourceManager.GetString("advanced_settings_global_resolver_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Resolver.
        /// </summary>
        internal static string advanced_settings_global_resolver_title {
            get {
                return ResourceManager.GetString("advanced_settings_global_resolver_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open plugin manager.
        /// </summary>
        internal static string advanced_settings_plugins_button {
            get {
                return ResourceManager.GetString("advanced_settings_plugins_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable extra settings with plugins.
        /// </summary>
        internal static string advanced_settings_plugins_text {
            get {
                return ResourceManager.GetString("advanced_settings_plugins_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        internal static string advanced_settings_plugins_title {
            get {
                return ResourceManager.GetString("advanced_settings_plugins_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download List.
        /// </summary>
        internal static string advanced_settings_refresh_resolver_button {
            get {
                return ResourceManager.GetString("advanced_settings_refresh_resolver_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the list of public resolvers (all downloads are validated with a minisgn signature).
        /// </summary>
        internal static string advanced_settings_refresh_resolver_text {
            get {
                return ResourceManager.GetString("advanced_settings_refresh_resolver_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh public resolver list.
        /// </summary>
        internal static string advanced_settings_refresh_resolver_title {
            get {
                return ResourceManager.GetString("advanced_settings_refresh_resolver_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TCP port 443 instead of UDP port 443 (TCP is slower than UDP).
        /// </summary>
        internal static string advanced_settings_transport_tcp_text {
            get {
                return ResourceManager.GetString("advanced_settings_transport_tcp_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport Settings.
        /// </summary>
        internal static string advanced_settings_transport_tcp_title {
            get {
                return ResourceManager.GetString("advanced_settings_transport_tcp_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall all services.
        /// </summary>
        internal static string advanced_settings_uninstall_button {
            get {
                return ResourceManager.GetString("advanced_settings_uninstall_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all installed windows services.
        /// </summary>
        internal static string advanced_settings_uninstall_text {
            get {
                return ResourceManager.GetString("advanced_settings_uninstall_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Services.
        /// </summary>
        internal static string advanced_settings_uninstall_title {
            get {
                return ResourceManager.GetString("advanced_settings_uninstall_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to building list . . ..
        /// </summary>
        internal static string blacklist_building_list {
            get {
                return ResourceManager.GetString("blacklist_building_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new address rule.
        /// </summary>
        internal static string blacklist_button_add_address {
            get {
                return ResourceManager.GetString("blacklist_button_add_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new local domain rule.
        /// </summary>
        internal static string blacklist_button_add_local_domain {
            get {
                return ResourceManager.GetString("blacklist_button_add_local_domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new remote domain rule (URL).
        /// </summary>
        internal static string blacklist_button_add_remote_domain {
            get {
                return ResourceManager.GetString("blacklist_button_add_remote_domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build address blacklist.
        /// </summary>
        internal static string blacklist_button_build_address {
            get {
                return ResourceManager.GetString("blacklist_button_build_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build domain blacklist.
        /// </summary>
        internal static string blacklist_button_build_domain {
            get {
                return ResourceManager.GetString("blacklist_button_build_domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove address entry.
        /// </summary>
        internal static string blacklist_button_remove_address {
            get {
                return ResourceManager.GetString("blacklist_button_remove_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove domain entry.
        /// </summary>
        internal static string blacklist_button_remove_domain {
            get {
                return ResourceManager.GetString("blacklist_button_remove_domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select address blacklist file.
        /// </summary>
        internal static string blacklist_button_select_address_blacklist {
            get {
                return ResourceManager.GetString("blacklist_button_select_address_blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select domain blacklist file.
        /// </summary>
        internal static string blacklist_button_select_domain_blacklist {
            get {
                return ResourceManager.GetString("blacklist_button_select_domain_blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entries.
        /// </summary>
        internal static string blacklist_entries {
            get {
                return ResourceManager.GetString("blacklist_entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set blacklist.
        /// </summary>
        internal static string blacklist_modal_empty_list_header {
            get {
                return ResourceManager.GetString("blacklist_modal_empty_list_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A blacklist file can not be empty.
        /// </summary>
        internal static string blacklist_modal_empty_list_text {
            get {
                return ResourceManager.GetString("blacklist_modal_empty_list_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New address rule.
        /// </summary>
        internal static string blacklist_modal_new_address_rule_header {
            get {
                return ResourceManager.GetString("blacklist_modal_new_address_rule_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: 172.16.144.8, 172.16.*, [fdb2:cd9e:c9f8:861a:c1ab:94e3:ef95:1ec0].
        /// </summary>
        internal static string blacklist_modal_new_address_rule_text {
            get {
                return ResourceManager.GetString("blacklist_modal_new_address_rule_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New local domain rule.
        /// </summary>
        internal static string blacklist_modal_new_local_domain_rule_header {
            get {
                return ResourceManager.GetString("blacklist_modal_new_local_domain_rule_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: *.example.com, ads.*, *sex*.
        /// </summary>
        internal static string blacklist_modal_new_local_domain_rule_text {
            get {
                return ResourceManager.GetString("blacklist_modal_new_local_domain_rule_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New remote domain rule.
        /// </summary>
        internal static string blacklist_modal_new_remote_domain_rule_header {
            get {
                return ResourceManager.GetString("blacklist_modal_new_remote_domain_rule_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt.
        /// </summary>
        internal static string blacklist_modal_new_remote_domain_rule_text {
            get {
                return ResourceManager.GetString("blacklist_modal_new_remote_domain_rule_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block addresses.
        /// </summary>
        internal static string block_plugin_sub_addresses_header {
            get {
                return ResourceManager.GetString("block_plugin_sub_addresses_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block addresses with custom rules (eg: 10.1.4.99, 172.16.*).
        /// </summary>
        internal static string block_plugin_sub_addresses_text {
            get {
                return ResourceManager.GetString("block_plugin_sub_addresses_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block domains.
        /// </summary>
        internal static string block_plugin_sub_domains_header {
            get {
                return ResourceManager.GetString("block_plugin_sub_domains_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block domains with local rules or remote files.
        /// </summary>
        internal static string block_plugin_sub_domains_text {
            get {
                return ResourceManager.GetString("block_plugin_sub_domains_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin returns a REFUSED response if the query name is in a list of blacklisted names, or if at least one of the returned IP addresses happens to be in a list of blacklisted IPs..
        /// </summary>
        internal static string block_plugin_text {
            get {
                return ResourceManager.GetString("block_plugin_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block addresses and domains.
        /// </summary>
        internal static string block_plugin_title {
            get {
                return ResourceManager.GetString("block_plugin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string cache_plugin_seconds {
            get {
                return ResourceManager.GetString("cache_plugin_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple, zero-configuration DNS response cache..
        /// </summary>
        internal static string cache_plugin_text {
            get {
                return ResourceManager.GetString("cache_plugin_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS response cache.
        /// </summary>
        internal static string cache_plugin_title {
            get {
                return ResourceManager.GetString("cache_plugin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTL (cache time).
        /// </summary>
        internal static string cache_plugin_ttl {
            get {
                return ResourceManager.GetString("cache_plugin_ttl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get some extra info about the resolvers (only IPv4).
        /// </summary>
        internal static string default_settings_analyse_button_tooltip {
            get {
                return ResourceManager.GetString("default_settings_analyse_button_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNSSEC.
        /// </summary>
        internal static string default_settings_dnssec {
            get {
                return ResourceManager.GetString("default_settings_dnssec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNSCrypt will listen on this port (default: 53).
        /// </summary>
        internal static string default_settings_info_port {
            get {
                return ResourceManager.GetString("default_settings_info_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (FQDN).
        /// </summary>
        internal static string default_settings_name {
            get {
                return ResourceManager.GetString("default_settings_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Cards.
        /// </summary>
        internal static string default_settings_network_cards {
            get {
                return ResourceManager.GetString("default_settings_network_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Logs.
        /// </summary>
        internal static string default_settings_no_logs {
            get {
                return ResourceManager.GetString("default_settings_no_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Resolver.
        /// </summary>
        internal static string default_settings_primary_header {
            get {
                return ResourceManager.GetString("default_settings_primary_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary DNSCrypt Service.
        /// </summary>
        internal static string default_settings_primary_service {
            get {
                return ResourceManager.GetString("default_settings_primary_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first resolver.
        /// </summary>
        internal static string default_settings_primary_text {
            get {
                return ResourceManager.GetString("default_settings_primary_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Key.
        /// </summary>
        internal static string default_settings_public_key {
            get {
                return ResourceManager.GetString("default_settings_public_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolver.
        /// </summary>
        internal static string default_settings_resolver {
            get {
                return ResourceManager.GetString("default_settings_resolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string default_settings_save_port {
            get {
                return ResourceManager.GetString("default_settings_save_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Resolver.
        /// </summary>
        internal static string default_settings_secondary_header {
            get {
                return ResourceManager.GetString("default_settings_secondary_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary DNSCrypt Service.
        /// </summary>
        internal static string default_settings_secondary_service {
            get {
                return ResourceManager.GetString("default_settings_secondary_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second resolver (optional).
        /// </summary>
        internal static string default_settings_secondary_text {
            get {
                return ResourceManager.GetString("default_settings_secondary_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Address.
        /// </summary>
        internal static string default_settings_server_address {
            get {
                return ResourceManager.GetString("default_settings_server_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string default_settings_services {
            get {
                return ResourceManager.GetString("default_settings_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hidden cards.
        /// </summary>
        internal static string default_settings_show_hidden_cards {
            get {
                return ResourceManager.GetString("default_settings_show_hidden_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string dialog_error_title {
            get {
                return ResourceManager.GetString("dialog_error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must run this application as administrator..
        /// </summary>
        internal static string dialog_message_bad_privileges {
            get {
                return ResourceManager.GetString("dialog_message_bad_privileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can`t load: {0} or {1}..
        /// </summary>
        internal static string dialog_message_missing_file {
            get {
                return ResourceManager.GetString("dialog_message_missing_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all the necessary files in dnscrypt proxy folder are found, reinstalling the application is recommended..
        /// </summary>
        internal static string dialog_message_missing_proxy_files {
            get {
                return ResourceManager.GetString("dialog_message_missing_proxy_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to refresh the resolver list..
        /// </summary>
        internal static string dialog_message_refresh_failed {
            get {
                return ResourceManager.GetString("dialog_message_refresh_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove all installed windows services?.
        /// </summary>
        internal static string dialog_message_uninstall {
            get {
                return ResourceManager.GetString("dialog_message_uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new Simple DNSCrypt version ({0}) available. The update is marked as critical, so you really should do the update now! Do you want to update now?.
        /// </summary>
        internal static string dialog_message_update_critical_text {
            get {
                return ResourceManager.GetString("dialog_message_update_critical_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Application Update.
        /// </summary>
        internal static string dialog_message_update_critical_title {
            get {
                return ResourceManager.GetString("dialog_message_update_critical_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new Simple DNSCrypt version ({0}) available. Do you want to update now?.
        /// </summary>
        internal static string dialog_message_update_standard_text {
            get {
                return ResourceManager.GetString("dialog_message_update_standard_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Update.
        /// </summary>
        internal static string dialog_message_update_standard_title {
            get {
                return ResourceManager.GetString("dialog_message_update_standard_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string dialog_plugins_save_button_tooltip {
            get {
                return ResourceManager.GetString("dialog_plugins_save_button_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        internal static string dialog_success_title {
            get {
                return ResourceManager.GetString("dialog_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Services.
        /// </summary>
        internal static string dialog_uninstall_title {
            get {
                return ResourceManager.GetString("dialog_uninstall_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer.
        /// </summary>
        internal static string dialog_update_installer {
            get {
                return ResourceManager.GetString("dialog_update_installer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        internal static string dialog_update_signature {
            get {
                return ResourceManager.GetString("dialog_update_signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        internal static string dialog_update_title {
            get {
                return ResourceManager.GetString("dialog_update_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string dialog_warning_title {
            get {
                return ResourceManager.GetString("dialog_warning_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv6 disabled.
        /// </summary>
        internal static string global_ipv6_disabled {
            get {
                return ResourceManager.GetString("global_ipv6_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If IPv6 connectivity is not available on your network, this plugin avoids waiting for responses about IPv6 addresses from upstream resolvers. This can improve your web browsing experience..
        /// </summary>
        internal static string ipv6_speed_plugin_text {
            get {
                return ResourceManager.GetString("ipv6_speed_plugin_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed up on missing IPv6.
        /// </summary>
        internal static string ipv6_speed_plugin_title {
            get {
                return ResourceManager.GetString("ipv6_speed_plugin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selected to local domain blacklist.
        /// </summary>
        internal static string log_button_add_to_blacklist {
            get {
                return ResourceManager.GetString("log_button_add_to_blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries in LiveLog:.
        /// </summary>
        internal static string log_entries {
            get {
                return ResourceManager.GetString("log_entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Blacklist Entry.
        /// </summary>
        internal static string log_modal_add_rule_header {
            get {
                return ResourceManager.GetString("log_modal_add_rule_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can modify the entry before you add them to the blacklist: .
        /// </summary>
        internal static string log_modal_add_rule_text {
            get {
                return ResourceManager.GetString("log_modal_add_rule_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Logfile.
        /// </summary>
        internal static string log_modal_no_log_file_header {
            get {
                return ResourceManager.GetString("log_modal_no_log_file_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no logfile to show. Please enable the logging plugin first..
        /// </summary>
        internal static string log_modal_no_log_file_text {
            get {
                return ResourceManager.GetString("log_modal_no_log_file_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a log folder.
        /// </summary>
        internal static string log_plugin_select_folder {
            get {
                return ResourceManager.GetString("log_plugin_select_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin logs the DNS queries received by the proxy.
        ///The logs are stored in a local file..
        /// </summary>
        internal static string log_plugin_text {
            get {
                return ResourceManager.GetString("log_plugin_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string log_plugin_title {
            get {
                return ResourceManager.GetString("log_plugin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        internal static string log_source {
            get {
                return ResourceManager.GetString("log_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string tab_about {
            get {
                return ResourceManager.GetString("tab_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        internal static string tab_advanced_settings {
            get {
                return ResourceManager.GetString("tab_advanced_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block and Blacklist.
        /// </summary>
        internal static string tab_block {
            get {
                return ResourceManager.GetString("tab_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Log.
        /// </summary>
        internal static string tab_log {
            get {
                return ResourceManager.GetString("tab_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Settings.
        /// </summary>
        internal static string tab_standard_settings {
            get {
                return ResourceManager.GetString("tab_standard_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available extensions.
        /// </summary>
        internal static string window_plugin_title {
            get {
                return ResourceManager.GetString("window_plugin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay tuned.
        /// </summary>
        internal static string window_update_title {
            get {
                return ResourceManager.GetString("window_update_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
